name: gem_changelog

on:
  workflow_call:
    secrets:
      rubygemsToken:
        description: A API token of rubygems.org. Required scope is `Index rubygems`.
        required: false

jobs:
  pre_job:
    runs-on: ubuntu-slim
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578
        with:
          paths: '["Gemfile.lock"]'

  gem_changelog:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - uses: kzkn/rubygems-changelog-url-action@v2
        with:
          githubToken: ${{ github.token }}
          rubygemsToken: ${{ secrets.rubygemsToken }}
