name: new_gems

on:
  workflow_call:

jobs:
  pre_job:
    runs-on: ubuntu-slim
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578
        with:
          paths: '["Gemfile"]'

  new_gems:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - uses: aki77/new-gems-action@v2
        with:
          token: ${{ github.token }}
