name: new_gems

on:
  workflow_call:

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@b8076051474d234b9bf70d23464609b88d271060
        with:
          paths: '["Gemfile"]'

  new_gems:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - uses: aki77/new-gems-action@v1
        with:
          token: ${{ github.token }}
