name: new_npm

on:
  workflow_call:

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f11521568414503656a5af807dc3018c012552c4
        with:
          paths: '["package.json"]'

  new_npm:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: hiwelo/new-dependencies-action@e4175e14484328f9ab56df91e420e90ad5031c08
        with:
          token: ${{ github.token }}
